Festat script updated and split with two
Hirlam/AccordDaTools pull request #30
Opened 2024-01-29 11:51 UTC by swapanmallicksmhi

Festat script updated and split with two
1. python3 festat_S1.py
2. sbatch festat_S2.job

2024-02-02 16:05 UTC, roelstappers requested changes

2024-02-02 16:05 UTC, roelstappers commented on scripts/festat_S1.py
> +        filelink = filecond.get(True,None)
can't this just be `filelink=filename[:-4] + str(fnumber).zfill(4)` ?

2024-02-08 09:32 UTC, swapanmallicksmhi commented on scripts/festat_S1.py
> +        filelink = filecond.get(True,None)
Hi @roelstappers 
Thanks for the comment. With the modification it is working same.
''' filelink=filename[:-4] + str(fnumber).zfill(4) '''
I add the modification now.

2024-02-08 10:05 UTC, roelstappers commented
> Thanks for the comment. With the modification it is working same.
> ''' filelink=filename[:-4] + str(fnumber).zfill(4) '''
> I add the modification now.

Thanks  @swapanmallicksmhi.  
For some reasons github shows this PR as changing 29 files. Can you try to merge the latest version of the develop branch of into your festat_stuff branch to see if that fixes it?

2024-02-08 10:30 UTC, closed without merging